// 
// Decompiled by Procyon v0.6.0
// 

package net.labymod.main;

import net.minecraft.util.ResourceLocation;

public class ModTextures
{
    public static final String TEXTURE_FOLDER = "labymod/textures/";
    public static final String SETTING = "labymod/textures/settings/";
    public static final String SETTING_GUI_CATEGORY_ICONS = "labymod/textures/settings/guicategory/";
    public static final String SETTING_CATEGORY_ICONS = "labymod/textures/settings/category/";
    public static final String SETTING_ICONS = "labymod/textures/settings/settings/";
    public static final String MODULE_ICONS = "labymod/textures/settings/modules/";
    public static final String SKIN_ICONS = "labymod/textures/settings/skin/";
    public static final String COSMETICS = "labymod/textures/cosmetics/";
    public static final String CHAT = "labymod/textures/chat/";
    public static final String MISC = "labymod/textures/misc/";
    public static final String BUTTONS = "labymod/textures/buttons/";
    public static final String BADGES = "labymod/textures/badges/";
    public static final ResourceLocation SETTINGS_MODULE_EDITOR_BG;
    public static final ResourceLocation SETTINGS_DEFAULT_USE_DEFAULT_SETTINGS;
    public static final ResourceLocation SETTINGS_DEFAULT_DISPLAY_KEY;
    public static final ResourceLocation SETTINGS_DEFAULT_GRID_MOVEMENT;
    public static final ResourceLocation SETTINGS_DEFAULT_ITEM_GRAVITY;
    public static final ResourceLocation SETTINGS_DEFAULT_GUI_SCALING;
    public static final ResourceLocation SETTINGS_DEFAULT_BACKGROUND;
    public static final ResourceLocation SETTINGS_DEFAULT_PADDING;
    public static final ResourceLocation COSMETIC_CAPE_STAR;
    public static final ResourceLocation COSMETIC_HALO;
    public static final ResourceLocation COSMETIC_XMAS;
    public static final ResourceLocation COSMETIC_CROWN;
    public static final ResourceLocation COSMETIC_WITCH;
    public static final ResourceLocation COSMETIC_BLAZE;
    public static final ResourceLocation COSMETIC_WITHER;
    public static final ResourceLocation COSMETIC_ENDER_DRAGON_CLASSIC;
    public static final ResourceLocation COSMETIC_ENDER_DRAGON;
    public static final ResourceLocation COSMETIC_SNOXH_EYE;
    public static final ResourceLocation COSMETIC_SNOXH_MASK;
    public static final ResourceLocation COSMETIC_BANDANA_DEFAULT;
    public static final ResourceLocation COSMETIC_HEADSET;
    public static final ResourceLocation COSMETIC_DOG;
    public static final ResourceLocation COSMETIC_RABBIT;
    public static final ResourceLocation COSMETIC_TAIL_WOLF;
    public static final ResourceLocation COSMETIC_TAIL_CAT;
    public static final ResourceLocation COSMETIC_ANTLER;
    public static final ResourceLocation COSMETIC_REDNOSE;
    public static final ResourceLocation COSMETIC_WINGS_STEAMPUNK;
    public static final ResourceLocation COSMETIC_WINGS_CRYSTAL;
    public static final ResourceLocation COSMETIC_DEVIL_HORNS;
    public static final ResourceLocation COSMETIC_BACKPACK;
    public static final ResourceLocation COSMETIC_STEGI;
    public static final ResourceLocation COSMETIC_REVED_ARM_COLORED;
    public static final ResourceLocation COSMETIC_REVED_ARM;
    public static final ResourceLocation COSMETIC_REVED_FLAME;
    public static final ResourceLocation COSMETIC_ABGEGRIEFT;
    public static final ResourceLocation COSMETIC_WINGS_CLOUD;
    public static final ResourceLocation COSMETIC_MASK_FACE;
    public static final ResourceLocation COSMETIC_WINGS_BUTTERFLY;
    public static final ResourceLocation COSMETIC_WINGS_BUTTERFLY_OVERLAY;
    public static final ResourceLocation COSMETIC_WATCH_CASE;
    public static final ResourceLocation COSMETIC_CAT_TAIL;
    public static final ResourceLocation COSMETIC_CAT_EARS;
    public static final ResourceLocation CHAT_TAB_SYMBOLS;
    public static final ResourceLocation CHAT_TAB_FILTER;
    public static final ResourceLocation CHAT_TAB_AUTOTEXT;
    public static final ResourceLocation CHAT_TAB_SHORTCUT;
    public static final ResourceLocation CHAT_TAB_PLAYERMENU;
    public static final ResourceLocation CHAT_TAB_GUI_EDITOR;
    public static final ResourceLocation BADGE_GROUP;
    public static final ResourceLocation BADGE_FAMILIAR;
    public static final ResourceLocation BADGE_GROUP_SMALL;
    public static final ResourceLocation BADGE_FAMILIAR_SMALL;
    public static final ResourceLocation MISC_HEAD_QUESTION;
    public static final ResourceLocation MISC_FEATURED;
    public static final ResourceLocation MISC_CROWN;
    public static final ResourceLocation MISC_PARTNER_CROWN;
    public static final ResourceLocation MISC_PARTY;
    public static final ResourceLocation MISC_MENU_POINT;
    public static final ResourceLocation MISC_ARROW;
    public static final ResourceLocation MISC_BLOCKED;
    public static final ResourceLocation MISC_MOUSE;
    public static final ResourceLocation BUTTON_ACCEPT;
    public static final ResourceLocation BUTTON_DENY;
    public static final ResourceLocation BUTTON_CHECKBOX;
    public static final ResourceLocation BUTTON_SIGNSEARCH;
    public static final ResourceLocation BUTTON_UPDATE;
    public static final ResourceLocation BUTTON_EXPAND;
    public static final ResourceLocation BUTTON_EXCLAMATION;
    public static final ResourceLocation BUTTON_QUESTION;
    public static final ResourceLocation BUTTON_CUSTOM;
    public static final ResourceLocation BUTTON_DOWNLOAD;
    public static final ResourceLocation BUTTON_TRASH;
    public static final ResourceLocation BUTTON_RESET;
    public static final ResourceLocation BUTTON_UNDO;
    public static final ResourceLocation BUTTON_LARGE;
    public static final ResourceLocation BUTTON_LARGE_PRESSED;
    public static final ResourceLocation BUTTON_LARGE_DISABLED;
    public static final ResourceLocation BUTTON_ADDON_SETTINGS;
    public static final ResourceLocation BUTTON_HOVER_DEFAULT;
    public static final ResourceLocation BUTTON_ADVANCED;
    public static final ResourceLocation LOGO_LABYMOD_LOGO;
    public static final ResourceLocation TITLE_LABYMOD_BANNER;
    public static final ResourceLocation TITLE_MOJANG_BANNER;
    public static final ResourceLocation ITEM_ARROW;
    public static final ResourceLocation ITEM_SWORD;
    public static final ResourceLocation ITEM_HELMET;
    public static final ResourceLocation ITEM_CHESTPLATE;
    public static final ResourceLocation ITEM_LEGGINGS;
    public static final ResourceLocation ITEM_BOOTS;
    public static final ResourceLocation ACHIEVEMENT;
    public static final ResourceLocation VOID;
    
    static {
        SETTINGS_MODULE_EDITOR_BG = new ResourceLocation("labymod/textures/settings/module_editor_bg.jpg");
        SETTINGS_DEFAULT_USE_DEFAULT_SETTINGS = new ResourceLocation("labymod/textures/settings/default/use_default_settings.png");
        SETTINGS_DEFAULT_DISPLAY_KEY = new ResourceLocation("labymod/textures/settings/default/display_key.png");
        SETTINGS_DEFAULT_GRID_MOVEMENT = new ResourceLocation("labymod/textures/settings/default/grid_movement.png");
        SETTINGS_DEFAULT_ITEM_GRAVITY = new ResourceLocation("labymod/textures/settings/default/item_gravity.png");
        SETTINGS_DEFAULT_GUI_SCALING = new ResourceLocation("labymod/textures/settings/default/gui_scaling.png");
        SETTINGS_DEFAULT_BACKGROUND = new ResourceLocation("labymod/textures/settings/default/background.png");
        SETTINGS_DEFAULT_PADDING = new ResourceLocation("labymod/textures/settings/default/padding.png");
        COSMETIC_CAPE_STAR = new ResourceLocation("labymod/textures/cosmetics/star.png");
        COSMETIC_HALO = new ResourceLocation("labymod/textures/cosmetics/halo.png");
        COSMETIC_XMAS = new ResourceLocation("labymod/textures/cosmetics/xmas.png");
        COSMETIC_CROWN = new ResourceLocation("labymod/textures/cosmetics/crown.png");
        COSMETIC_WITCH = new ResourceLocation("labymod/textures/cosmetics/flags/default.png");
        COSMETIC_BLAZE = new ResourceLocation("textures/entity/blaze.png");
        COSMETIC_WITHER = new ResourceLocation("textures/entity/wither/wither.png");
        COSMETIC_ENDER_DRAGON_CLASSIC = new ResourceLocation("textures/entity/enderdragon/dragon.png");
        COSMETIC_ENDER_DRAGON = new ResourceLocation("labymod/textures/cosmetics/dragon.png");
        COSMETIC_SNOXH_EYE = new ResourceLocation("labymod/textures/cosmetics/snoxh/eye.png");
        COSMETIC_SNOXH_MASK = new ResourceLocation("labymod/textures/cosmetics/snoxh/mask.png");
        COSMETIC_BANDANA_DEFAULT = new ResourceLocation("labymod/textures/cosmetics/bandana.png");
        COSMETIC_HEADSET = new ResourceLocation("labymod/textures/cosmetics/headset.png");
        COSMETIC_DOG = new ResourceLocation("labymod/textures/cosmetics/dog.png");
        COSMETIC_RABBIT = new ResourceLocation("labymod/textures/cosmetics/rabbit.png");
        COSMETIC_TAIL_WOLF = new ResourceLocation("labymod/textures/cosmetics/wolftail.png");
        COSMETIC_TAIL_CAT = new ResourceLocation("labymod/textures/cosmetics/cattail.png");
        COSMETIC_ANTLER = new ResourceLocation("labymod/textures/cosmetics/antler.png");
        COSMETIC_REDNOSE = new ResourceLocation("labymod/textures/cosmetics/rednose.png");
        COSMETIC_WINGS_STEAMPUNK = new ResourceLocation("labymod/textures/cosmetics/steampunk.png");
        COSMETIC_WINGS_CRYSTAL = new ResourceLocation("labymod/textures/cosmetics/crystal.png");
        COSMETIC_DEVIL_HORNS = new ResourceLocation("labymod/textures/cosmetics/devilhorns.png");
        COSMETIC_BACKPACK = new ResourceLocation("labymod/textures/cosmetics/backpack.png");
        COSMETIC_STEGI = new ResourceLocation("labymod/textures/cosmetics/stegi.png");
        COSMETIC_REVED_ARM_COLORED = new ResourceLocation("labymod/textures/cosmetics/reved/arm_colored.png");
        COSMETIC_REVED_ARM = new ResourceLocation("labymod/textures/cosmetics/reved/arm.png");
        COSMETIC_REVED_FLAME = new ResourceLocation("labymod/textures/cosmetics/reved/flame.png");
        COSMETIC_ABGEGRIEFT = new ResourceLocation("labymod/textures/cosmetics/abgegrieft.png");
        COSMETIC_WINGS_CLOUD = new ResourceLocation("labymod/textures/cosmetics/cloudwings.png");
        COSMETIC_MASK_FACE = new ResourceLocation("labymod/textures/cosmetics/facemask.png");
        COSMETIC_WINGS_BUTTERFLY = new ResourceLocation("labymod/textures/cosmetics/butterfly.png");
        COSMETIC_WINGS_BUTTERFLY_OVERLAY = new ResourceLocation("labymod/textures/cosmetics/butterfly_overlay.png");
        COSMETIC_WATCH_CASE = new ResourceLocation("labymod/textures/cosmetics/watch_case.png");
        COSMETIC_CAT_TAIL = new ResourceLocation("labymod/textures/cosmetics/cat_tail.png");
        COSMETIC_CAT_EARS = new ResourceLocation("labymod/textures/cosmetics/cat_ears.png");
        CHAT_TAB_SYMBOLS = new ResourceLocation("labymod/textures/chat/symbols.png");
        CHAT_TAB_FILTER = new ResourceLocation("labymod/textures/chat/filter.png");
        CHAT_TAB_AUTOTEXT = new ResourceLocation("labymod/textures/chat/autotext.png");
        CHAT_TAB_SHORTCUT = new ResourceLocation("labymod/textures/chat/shortcut.png");
        CHAT_TAB_PLAYERMENU = new ResourceLocation("labymod/textures/chat/playermenu.png");
        CHAT_TAB_GUI_EDITOR = new ResourceLocation("labymod/textures/chat/gui_editor.png");
        BADGE_GROUP = new ResourceLocation("labymod/textures/badges/group_badge.png");
        BADGE_FAMILIAR = new ResourceLocation("labymod/textures/badges/familiar.png");
        BADGE_GROUP_SMALL = new ResourceLocation("labymod/textures/badges/group_badge_small.png");
        BADGE_FAMILIAR_SMALL = new ResourceLocation("labymod/textures/badges/familiar_small.png");
        MISC_HEAD_QUESTION = new ResourceLocation("labymod/textures/misc/question.png");
        MISC_FEATURED = new ResourceLocation("labymod/textures/misc/featured.png");
        MISC_CROWN = new ResourceLocation("labymod/textures/misc/crown.png");
        MISC_PARTNER_CROWN = new ResourceLocation("labymod/textures/misc/partner_crown.png");
        MISC_PARTY = new ResourceLocation("labymod/textures/misc/party.png");
        MISC_MENU_POINT = new ResourceLocation("labymod/textures/misc/menu_point.png");
        MISC_ARROW = new ResourceLocation("labymod/textures/misc/arrow.png");
        MISC_BLOCKED = new ResourceLocation("labymod/textures/misc/blocked.png");
        MISC_MOUSE = new ResourceLocation("labymod/textures/misc/mouse.png");
        BUTTON_ACCEPT = new ResourceLocation("labymod/textures/buttons/accept.png");
        BUTTON_DENY = new ResourceLocation("labymod/textures/buttons/deny.png");
        BUTTON_CHECKBOX = new ResourceLocation("labymod/textures/buttons/checkbox.png");
        BUTTON_SIGNSEARCH = new ResourceLocation("labymod/textures/buttons/sign_search.png");
        BUTTON_UPDATE = new ResourceLocation("labymod/textures/buttons/update.png");
        BUTTON_EXPAND = new ResourceLocation("labymod/textures/buttons/expand.png");
        BUTTON_EXCLAMATION = new ResourceLocation("labymod/textures/buttons/exclamation_mark.png");
        BUTTON_QUESTION = new ResourceLocation("labymod/textures/buttons/question_mark.png");
        BUTTON_CUSTOM = new ResourceLocation("labymod/textures/buttons/button_custom.png");
        BUTTON_DOWNLOAD = new ResourceLocation("labymod/textures/buttons/download.png");
        BUTTON_TRASH = new ResourceLocation("labymod/textures/buttons/trash.png");
        BUTTON_RESET = new ResourceLocation("labymod/textures/buttons/reset.png");
        BUTTON_UNDO = new ResourceLocation("labymod/textures/buttons/undo.png");
        BUTTON_LARGE = new ResourceLocation("labymod/textures/buttons/button_large.png");
        BUTTON_LARGE_PRESSED = new ResourceLocation("labymod/textures/buttons/button_large_pressed.png");
        BUTTON_LARGE_DISABLED = new ResourceLocation("labymod/textures/buttons/button_large_disabled.png");
        BUTTON_ADDON_SETTINGS = new ResourceLocation("labymod/textures/buttons/addon_settings.png");
        BUTTON_HOVER_DEFAULT = new ResourceLocation("labymod/textures/buttons/hover_default.png");
        BUTTON_ADVANCED = new ResourceLocation("labymod/textures/buttons/advanced.png");
        LOGO_LABYMOD_LOGO = new ResourceLocation("labymod/textures/labymod_logo.png");
        TITLE_LABYMOD_BANNER = new ResourceLocation("labymod/textures/title/labymod_banner.png");
        TITLE_MOJANG_BANNER = new ResourceLocation("labymod/textures/title/mojang.png");
        ITEM_ARROW = new ResourceLocation("labymod/textures/items/arrow.png");
        ITEM_SWORD = new ResourceLocation("labymod/textures/items/sword.png");
        ITEM_HELMET = new ResourceLocation("labymod/textures/items/helmet.png");
        ITEM_CHESTPLATE = new ResourceLocation("labymod/textures/items/chestplate.png");
        ITEM_LEGGINGS = new ResourceLocation("labymod/textures/items/leggings.png");
        ITEM_BOOTS = new ResourceLocation("labymod/textures/items/boots.png");
        ACHIEVEMENT = new ResourceLocation("labymod/textures/achievement_background.png");
        VOID = new ResourceLocation("labymod/textures/void.png");
    }
}
